config/routes.rb
Rails.application.routes.draw do

match 'attendances/all/edit' => 'attendances#edit_all', :as => :edit_all, :via => :get
match 'attendances/all' => 'attendances#update_all', :as => :update_all, :via => :put

  get '/about' => 'home#author'
  
  get 'profiles/profileview' =>'profiles#profileview'
  
  resources :profiles
     
  get 'adminprofile/champs' => 'adminprofile#champs'

  get 'adminprofile/studentbelts' => 'adminprofile#studentbelts'

  get 'adminprofile/profile' => 'adminprofile#profile'

  get 'adminprofile/listofstudents' => 'adminprofile#listofstudents'

  get 'adminprofile/newbatch' => 'adminprofile#newbatch'

  get 'adminprofile/selectbatch' => 'adminprofile#selectbatch'

  devise_for :users, controllers: {registrations: 'users/registrations'}
  

  root 'home#homepage'

  resources :attendances
  resources :beltgradings
  resources :events
  resources :championships
  

  post 'activatestudent' => "adminprofile#activatestudent"

  devise_scope :user do get '/users/sign_out' => 'devise/sessions#destroy'
  end  

end

app/models/championship.rb
class Championship < ActiveRecord::Base

belongs_to :user

self.inheritance_column = nil

validates_presence_of :name, :type, :weight_category, :group, :poomsae_paticipation, :events, :fight_won, :fight_played, :rewards, :medal_g, :medal_s, :medal_b, :medal_n

has_attached_file :pic, styles: {
    thumb: '100x100>',
    square: '200x200#',
    medium: '300x300>'
  }

  
validates_attachment_content_type :pic, content_type: /\Aimage\/.*\Z/

end

app/controllers/championships_controller.rb
class ChampionshipsController < ApplicationController

 before_action :check_user 

  before_action :set_championship, only: [:show, :edit, :update, :destroy]

  # GET /championships
  # GET /championships.json

  def index
    @championships = Championship.all
  end

  # GET /championships/1
  # GET /championships/1.json
  def show
  end

  # GET /championships/new
  def new
    @championship = Championship.new
    #@user = User.all.where("id=?", params[:id])
    @championship.user_id = params[:user_id]
    #@championship.user_id = @user.id
    #@championship.name = @user.name 
    


  end

  # GET /championships/1/edit
  def edit
  end

  # POST /championships
  # POST /championships.json
  def create
    @championship = Championship.new(championship_params)

    respond_to do |format|
      if @championship.save
        format.html { redirect_to @championship, notice: 'Championship was successfully created.' }
        format.json { render :show, status: :created, location: @championship }
      else
        format.html { render :new }
        format.json { render json: @championship.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /championships/1
  # PATCH/PUT /championships/1.json
  def update
    respond_to do |format|
      if @championship.update(championship_params)
        format.html { redirect_to @championship, notice: 'Championship was successfully updated.' }
        format.json { render :show, status: :ok, location: @championship }
      else
        format.html { render :edit }
        format.json { render json: @championship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /championships/1
  # DELETE /championships/1.json
  def destroy
    @championship.destroy
    respond_to do |format|
      format.html { redirect_to championships_url, notice: 'Championship was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_championship
      @championship = Championship.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def championship_params
      params.require(:championship).permit(:name, :type, :weight_category, :group, :poomsae_paticipation, :events, :fight_won, :fight_played, :rewards, :medal_g, :medal_s, :medal_b, :medal_n, :user_id, :pic)
    end
end

app/helpers/championships_helper.rb
module ChampionshipsHelper
end

app/views/championships/_form.html.erb
<div style="padding-left:20px; padding-top: 20px;">

<%= form_for(@championship) do |f| %>

  <% if @championship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@championship.errors.count, "error") %> prohibited this championship from being saved:</h2>
      <ul>
      <% @championship.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table>

    <%= f.hidden_field :user_id %>

    <tr class="field">
      <td><%= f.label :name %></td>
      <td><%= f.text_field :name, :value => @championship.user.profile.name %></td>
    </tr>
    
    <tr class="field">
      <td><%= f.label :type %></td>
      <td><%= f.select :type, ['Class', 'District','State', 'National' ]%></td>
    </tr>

    <tr class="field">
      <td><%= f.label :weight_category %></td>
      <td><%= f.text_field :weight_category %></td>
    </tr>

    <tr class="field">
      <td><%= f.label :group %></td>
      <td><%= f.text_field :group %></td>
    </tr>

    <tr class="field">
      <td><%= f.label :poomsae_paticipation %></td>
      <td><%= f.select :poomsae_paticipation, ['Group', 'Individual', 'Both']%></td>
    </tr>

    <tr class="field">
      <td><%= f.label :events %></td>
      <td><%= f.text_field :events %></td>
    </tr>

    <tr class="field">
      <td><%= f.label :fight_won %></td>
      <td><%= f.text_field :fight_won %></td>
    </tr>

    <tr class="field">
      <td><%= f.label :fight_played %></td>
      <td><%= f.text_field :fight_played %></td>
    </tr>

    <tr class="field">
      <td><%= f.label :rewards %></td>
      <td><%= f.text_field :rewards %></td>
    </tr>

    <tr class="field">
      <td><%= f.label :medal_g %></td>
      <td><%= f.text_field :medal_g %></td>
    </tr>

    <tr class="field">
      <td><%= f.label :medal_s %></td>
      <td><%= f.text_field :medal_s %></td>
    </tr>

    <tr class="field">
      <td><%= f.label :medal_b %></td>
      <td><%= f.text_field :medal_b %></td>
    </tr>

    <tr class="field">
      <td><%= f.label :medal_n %></td>
      <td><%= f.text_field :medal_n %></td>
    </tr>

    <tr class="field">
      <td><%= f.label :Upload_photo %></td>
      <td><%= f.file_field :pic %></td>
    </tr>

    <tr class="actions">
      <td></td>  
      <td><%= f.submit  "Create", :class => 'btn btn-primary-ln' %></td>
    </tr>

    <% end %>

  </table>

</div>

app/views/championships/edit.html.erb
<div style="padding-top: 40px"><h1>Editing Championship</h1></div>

<%= render 'form' %>

<%= link_to 'Show', @championship %> | <%= link_to 'Back', championships_path %>

app/views/championships/index.html.erb
<div style="padding-left: 20px;padding-top: 60px">
<p id="notice"><%= notice %></p>

<h1>Listing Championships</h1>
<div class="table-responsive" style="padding-top: 20px">
<table class="table table-hover" style="font-size:15px; width:500px">
  <thead>
    <tr>
      <th>Name</th>
      <th>Type</th>
      <th>Weight category</th>
      <th>Group</th>
      <th>Poomsae paticipation</th>
      <th>Events</th>
      <th>Fight_won</th>
      <th>Fight_played</th>
      <th>Rewards</th>
      <th>Medal_g</th>
      <th>Medal_s</th>
      <th>Medal_b</th>
      <th>Medal_n</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @championships.each do |championship| %>
      <tr>
        <td><%= championship.name %></td>
        <td><%= championship.type %></td>
        <td><%= championship.weight_category %></td>
        <td><%= championship.group %></td>
        <td><%= championship.poomsae_paticipation %></td>
        <td><%= championship.events %></td>
        <td><%= championship.fight_won %></td>
        <td><%= championship.fight_played %></td>
        <td><%= championship.rewards %></td>
        <td><%= championship.medal_g %></td>
        <td><%= championship.medal_s %></td>
        <td><%= championship.medal_b %></td>
        <td><%= championship.medal_n %></td>
        <td><%= link_to 'Show', championship %></td>
        <td><%= link_to 'Edit', edit_championship_path(championship) %></td>
        <td><%= link_to 'Destroy', championship, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>

<%= link_to 'New Championship', new_championship_path %> | <%= link_to 'back to dashboard', adminprofile_profile_path %>
</div>

app/views/championships/new.html.erb
<div style="padding-top: 40px"><h1>New Championship</h1></div>

<%= render 'form' %>

<div style="padding-left: 60px; padding-bottom: 40px;"><h3><%= link_to 'Back', championships_path %><h3></div>

app/views/championships/show.html.erb
<div style="padding-left: 20px;padding-top: 60px">
<p id="notice"><%= notice %></p>
<%= image_tag @championship.pic.url(:square) %>
<p>
  <strong>Name:</strong>
  <%= @championship.name %>
</p>

<p>
  <strong>Type:</strong>
  <%= @championship.type %>
</p>

<p>
  <strong>Weight category:</strong>
  <%= @championship.weight_category %>
</p>

<p>
  <strong>Group:</strong>
  <%= @championship.group %>
</p>

<p>
  <strong>Poomsae paticipation:</strong>
  <%= @championship.poomsae_paticipation %>
</p>

<p>
  <strong>Events:</strong>
  <%= @championship.events %>
</p>

<p>
  <strong>Fight won:</strong>
  <%= @championship.fight_won %>
</p>

<p>
  <strong>Fight played:</strong>
  <%= @championship.fight_played %>
</p>

<p>
  <strong>Rewards:</strong>
  <%= @championship.rewards %>
</p>

<p>
  <strong>Medal g:</strong>
  <%= @championship.medal_g %>
</p>

<p>
  <strong>Medal s:</strong>
  <%= @championship.medal_s %>
</p>

<p>
  <strong>Medal b:</strong>
  <%= @championship.medal_b %>
</p>

<p>
  <strong>Medal n:</strong>
  <%= @championship.medal_n %>
</p>

<%= link_to 'Edit', edit_championship_path(@championship) %> |
<%= link_to 'Back', championships_path %>
</br><%= link_to 'back to dashboard', adminprofile_profile_path %>
</div>