config/routes.rb
Rails.application.routes.draw do

match 'attendances/all/edit' => 'attendances#edit_all', :as => :edit_all, :via => :get
match 'attendances/all' => 'attendances#update_all', :as => :update_all, :via => :put

  get '/about' => 'home#author'
  
  get 'profiles/profileview' =>'profiles#profileview'
  
  resources :profiles
     
  get 'adminprofile/champs' => 'adminprofile#champs'

  get 'adminprofile/studentbelts' => 'adminprofile#studentbelts'

  get 'adminprofile/profile' => 'adminprofile#profile'

  get 'adminprofile/listofstudents' => 'adminprofile#listofstudents'

  get 'adminprofile/newbatch' => 'adminprofile#newbatch'

  get 'adminprofile/selectbatch' => 'adminprofile#selectbatch'

  devise_for :users, controllers: {registrations: 'users/registrations'}
  

  root 'home#homepage'

  resources :attendances
  resources :beltgradings
  resources :events
  resources :championships
  

  post 'activatestudent' => "adminprofile#activatestudent"

  devise_scope :user do get '/users/sign_out' => 'devise/sessions#destroy'
  end  

end

app/models/event.rb
class Event < ActiveRecord::Base

self.inheritance_column = nil

serialize :team_manager
serialize :team_coach
serialize :team_officials

before_validation do |event|

event.team_manager.reject!(&:blank?) if event.team_manager
event.team_coach.reject!(&:blank?) if event.team_coach
event.team_officials.reject!(&:blank?) if event.team_officials

end

has_attached_file :picture, styles: {
    thumb: '100x100>',
    square: '200x200#',
    medium: '300x300>'
  }

  
validates_attachment_content_type :picture, content_type: /\Aimage\/.*\Z/


end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :check_user
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :type, :location, :event_date, :picture, {:team_manager => []}, {:team_coach =>[]}, {:team_officials => []}, :team_positions)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
  <div>
  <%= form_for(@event) do |f| %>
    <% if @event.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>
        <ul>
        <% @event.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <table>

    <tr class="field">
      <td><%= f.label :name %></td>
      <td><%= f.text_field :name %></td>
    </tr>

    <tr class="field">
      <td><%= f.label :type %></td>
      <td><%= f.select :type, ['Class', 'District','State', 'National' ]%></td>
    </tr>

    <tr class="field">
      <td><%= f.label :location %></td>
      <td><%= f.text_field :location %></td>
    </tr>
    
    <tr class="field">
      <td><%= f.label :event_date %><br></td>
      <td><%= f.date_select :event_date %></td>
    </tr>

    <tr class="field">
      <td><%= f.label :team_manager %></td>
      <td><%= f.select :team_manager, Profile.all.collect {|x| [x.name]}, {:include_blank => "Select One" }, { :multiple => true}%></td>
    </tr>

    <tr class="field">
    <td><%= f.label :team_coach %></td>
     <td><%= f.select :team_coach, Profile.all.collect {|x| [x.name]}, {:include_blank => "Select One" }, { :multiple => true}%></td>
    </tr>

    <tr class="field">
      <td><%= f.label :team_officials %></td>
      <td><%= f.select :team_officials, Profile.all.collect {|x| [x.name]}, {:include_blank => "Select One" }, { :multiple => true}%></td>
    </tr>

    <tr class="field">
      <td><%= f.label :team_positions %></td>
      <td><%= f.number_field :team_positions %></td>
    </tr>

    <tr class="field">
      <td><%= f.label :Upload_photo %></td>
      <td><%= f.file_field :picture %></td>
    </tr>
    
    <tr class="actions">
      <td>&nbsp</td>
      <td><%= f.submit "Create event", :class => 'btn btn-primary-ln' %></td>
      <td><%= link_to 'Back', events_path %></td>
    </tr>

    <% end %>

    </table>

</div>

app/views/events/edit.html.erb
<div style="padding-left: 40px; padding-top: 60px; padding-bottom: 40px">
	<h1>Editing Event</h1>
	<%= render 'form' %>
	<%= link_to 'Show', @event %> |
	<%= link_to 'Back', events_path %>
</div>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>
<br><br>
<h1>Listing Events</h1>
<div class="table-responsive" style="padding-top: 20px">
<table class="table table-hover" style="font-size:18px">
  <thead>
    <tr>
      <th>Name</th>
      <th>Type</th>
      <th>Location</th>
      <th>Event_date</th>
      <th>Team_manager</th>
      <th>Team_coach</th>
      <th>Team_officials</th>
      <th>Team_positions</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.name %></td>
        <td><%= event.type %></td>
        <td><%= event.location %></td>
        <td><%= event.event_date %></td>
        <td>
        <% event.team_manager.each do |x| %>
        <%= x %>
        <% end %>
        </td>
        <td>
        <% event.team_coach.each do |x| %>
        <%= x %>
        <% end %>
        </td>
        <td>
        <% event.team_officials.each do |x| %>
        <%= x %>
        <% end %>
        </td>
        <td><%= event.team_positions %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<div style="padding-left: 20px">
<%= link_to 'New Event', new_event_path %> | <%= link_to 'back to dashboard', adminprofile_profile_path %>
</div>

app/views/events/new.html.erb
<div style="padding-left: 40px; padding-top: 60px; padding-bottom: 40px">
	<h1>New Event</h1>
	<%= render 'form' %>
</div>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>
<%= image_tag @event.picture.url(:square) %>
<p>
  <strong>Name:</strong>
  <%= @event.name %>
</p>

<p>
  <strong>Type:</strong>
  <%= @event.type %>
</p>

<p>
  <strong>Location:</strong>
  <%= @event.location %>
</p>

<p>
  <strong>Event date:</strong>
  <%= @event.event_date %>
</p>

<p>
  <strong>Team manager:</strong>
  <%= @event.team_manager %>
</p>

<p>
  <strong>Team coach:</strong>
  <%= @event.team_coach %>
</p>

<p>
  <strong>Team officials:</strong>
  <%= @event.team_officials %>
</p>

<p>
  <strong>Team positions:</strong>
  <%= @event.team_positions %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>
</br><%= link_to 'back to dashboard', adminprofile_profile_path %>