config/routes.rb
Rails.application.routes.draw do

match 'attendances/all/edit' => 'attendances#edit_all', :as => :edit_all, :via => :get
match 'attendances/all' => 'attendances#update_all', :as => :update_all, :via => :put

  get '/about' => 'home#author'
  
  get 'profiles/profileview' =>'profiles#profileview'
  
  resources :profiles
     
  get 'adminprofile/champs' => 'adminprofile#champs'

  get 'adminprofile/studentbelts' => 'adminprofile#studentbelts'

  get 'adminprofile/profile' => 'adminprofile#profile'

  get 'adminprofile/listofstudents' => 'adminprofile#listofstudents'

  get 'adminprofile/newbatch' => 'adminprofile#newbatch'

  get 'adminprofile/selectbatch' => 'adminprofile#selectbatch'

  devise_for :users, controllers: {registrations: 'users/registrations'}
  

  root 'home#homepage'

  resources :attendances
  resources :beltgradings
  resources :events
  resources :championships
  

  post 'activatestudent' => "adminprofile#activatestudent"

  devise_scope :user do get '/users/sign_out' => 'devise/sessions#destroy'
  end  

end

app/controllers/adminprofile_controller.rb
class AdminprofileController < ApplicationController

before_action :check_user

def profile



end


def listofstudents

@user = User.all

end


def newbatch

end

def selectbatch

end

def activatestudent

@post = User.find(params[:id])

if @post.profile.status ==nil
@post.profile.update_attribute(:status, "active")
#@attendance = Attendance.new(:user_id => params[:id])
#@attendance.save
redirect_to adminprofile_listofstudents_path, :notice => "column is updated"

end

end

# this method is to display students who have paid fee and will be adding belts 

def studentbelts

@user = Profile.all.where("status =?", "active")

end

def champs
 	
 @user = Profile.all.where("status=?", "active") 

end

end

app/helpers/adminprofile_helper.rb
module AdminprofileHelper
end

app/views/adminprofile/champs.html.erb
<center>
<div class="container" style="padding-top: 75px; padding-left: 20px;">
  <h1> You can add championships to students </h1>

<div class="table-responsive" style="padding-top: 20px">
<table class="table table-hover" style="font-size:20px; width:800px">
  <thead>
    <tr>
      <th> Name </th>
      <th> Belts </th>
      <th> &nbsp </th>
    </tr>
  </thead>
  
  <tbody>
    <% @user.each do |post| %>
      <tr>
        <td> <%= post.name %> </td>
        <td> no belts </td>
        <td> <%=link_to "Add championships", new_championship_path(:user_id => post.id) %> </td>
      </tr>
      <% end %>
  </tbody>
</table>
</div>
</div>
</center>

app/views/adminprofile/listofstudents.html.erb
<center>
<div style="padding-top: 40px"><h1> List of registered students </h1></div>

<div class="table-responsive" style="padding-top: 20px">
<table class="table table-hover" style="font-size:20px; width:800px">
  <thead>
    <tr>
      <th>Student Name</th>
      <th>email_id  </th>
      <th>phone_number </th>
      <th>status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user.each do |post| %>
      <tr>
        <td><%= post.profile.name %></td>
        <td><%= post.email %></td>
        <td><%= post.profile.phone_number %></td>
        <% if post.profile.status == nil %>
        <td><%= button_to 'active', {:controller => 'adminprofile' , :action => 'activatestudent', :method => :PUT, :id => post.id}, 
        :class => 'btn btn-primary-ln' %></td>
        <% else %>
        <td>&nbsp;&nbsp; active </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</center>

app/views/adminprofile/newbatch.html.erb
<h1>create new batch of students</h1>

app/views/adminprofile/profile.html.erb
<div style="padding-top:75px">
<h1> Hello Admin </h1>
  <div class="container" style="padding-left:100px">
  <div class="row placeholders">
      <div class="col-xs-6 col-sm-4 placeholder">
        <%= link_to(image_tag("/huha.png", :width => "140", :height =>"140"), adminprofile_champs_path) %>
        <h4>Add new championships</h4>
      </div>

      <div class="col-xs-6 col-sm-4 placeholder">
        <%= link_to(image_tag("/huha.png", :width => "140", :height =>"140"), new_event_path) %>
        <h4>Add new events</h4>
      </div>

      <div class="col-xs-6 col-sm-4 placeholder">
        <%= link_to(image_tag("/huha.png", :width => "140", :height =>"140"), adminprofile_listofstudents_path) %>
        <h4>View list of registered students</h4>
      </div>

      <div class="col-xs-6 col-sm-4 placeholder">
        <%= link_to(image_tag("/huha.png", :width => "140", :height =>"140"), adminprofile_newbatch_path) %>
        <h4>Create new batch</h4>
      </div>

      <div class="col-xs-6 col-sm-4 placeholder">
        <%= link_to(image_tag("/huha.png", :width => "140", :height =>"140"), adminprofile_selectbatch_path) %>
        <h4>Fill attendence</h4>
      </div>

      <div class="col-xs-6 col-sm-4 placeholder">
        <%= link_to(image_tag("/huha.png", :width => "140", :height =>"140"), adminprofile_studentbelts_path)%>
        <h4>Belt gradings</h4>
      </div>

    </div>
</div>

app/views/adminprofile/selectbatch.html.erb
<h2>select batch you want to fill attendance </h1>

app/views/adminprofile/studentbelts.html.erb
<h1> List of paid students </h1>


<div class="table-responsive" style="padding-top: 20px">
<table class="table table-hover" style="font-size:20px; width:800px">
  <thead>
    <tr>
      <th>Student Name</th>
      <th>belts</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user.each do |post| %>
      <tr>
        <td><%= post.name %></td>
        <td>no belts</td>
        <td>&nbsp<%=link_to "add belt", new_beltgrading_path(:user_id => post.id) %></td>
      </tr>
      <% end %>
  </tbody>
</table>