config/routes.rb
Rails.application.routes.draw do

match 'attendances/all/edit' => 'attendances#edit_all', :as => :edit_all, :via => :get
match 'attendances/all' => 'attendances#update_all', :as => :update_all, :via => :put

  get '/about' => 'home#author'
  
  get 'profiles/profileview' =>'profiles#profileview'
  
  resources :profiles
     
  get 'adminprofile/champs' => 'adminprofile#champs'

  get 'adminprofile/studentbelts' => 'adminprofile#studentbelts'

  get 'adminprofile/profile' => 'adminprofile#profile'

  get 'adminprofile/listofstudents' => 'adminprofile#listofstudents'

  get 'adminprofile/newbatch' => 'adminprofile#newbatch'

  get 'adminprofile/selectbatch' => 'adminprofile#selectbatch'

  devise_for :users, controllers: {registrations: 'users/registrations'}
  

  root 'home#homepage'

  resources :attendances
  resources :beltgradings
  resources :events
  resources :championships
  

  post 'activatestudent' => "adminprofile#activatestudent"

  devise_scope :user do get '/users/sign_out' => 'devise/sessions#destroy'
  end  

end

app/models/attendance.rb
class Attendance < ActiveRecord::Base

belongs_to :user

end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  
  before_action :check_user
  before_action :set_attendance, only: [:show, :edit, :update, :destroy]

  # GET /attendances
  # GET /attendances.json
  def index
    @attendances = Attendance.all
    @users = User.all
  end

  # GET /attendances/1
  # GET /attendances/1.json
  def show
  end

  # GET /attendances/new
  def new
    @attendance = Attendance.new
  end

  # GET /attendances/1/edit
  
  def edit_all
    @attendance = Attendance.all
  end

  def update_all
 params['attendance'].keys.each do |id|
@user = Attendance.find(id.to_i)
@user.update_attributes(user_params(id))
end
redirect_to(root_url)
end

  def edit
  
  end

  # POST /attendances
  # POST /attendances.json
  def create
    @attendance = Attendance.new(attendance_params)

    respond_to do |format|
      if @attendance.save
        format.html { redirect_to @attendance, notice: 'Attendance was successfully created.' }
        format.json { render :show, status: :created, location: @attendance }
      else
        format.html { render :new }
        format.json { render json: @attendance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /attendances/1
  # PATCH/PUT /attendances/1.json


  def update
    
    respond_to do |format|


      if @attendance.update(attendance_params)
        format.html { redirect_to @attendance, notice: 'Attendance was successfully updated.' }
        format.json { render :show, status: :ok, location: @attendance }
      else
        format.html { render :edit }
        format.json { render json: @attendance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attendances/1
  # DELETE /attendances/1.json
  def destroy
    @attendance.destroy
    respond_to do |format|
      format.html { redirect_to attendances_url, notice: 'Attendance was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attendance
      @attendance = Attendance.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
def user_params(id)
params.require(:attendance).fetch(id).permit( :present_days, :total_days, :user_id )
end

    def attendance_params
      params.require(:attendance).permit(:present_days, :total_days, :user_id)
    end
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/views/attendances/_form.html.erb
<div class="padding-left:10px; padding-top: 60px ">
<%= form_for(@attendance) do |f| %>
  <% if @attendance.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@attendance.errors.count, "error") %> prohibited this attendance from being saved:</h2>

      <ul>
      <% @attendance.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :present_days %><br>
    <%= f.number_field :present_days %>
  </div>
  <div class="field">
    <%= f.label :total_days %><br>
    <%= f.number_field :total_days %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/attendances/edit.html.erb
<div style="padding-left: 10px; padding-top: 60px">
<%= form_for(@attendance) do |f| %>
  <% if @attendance.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@attendance.errors.count, "error") %> prohibited this attendance from being saved:</h2>

      <ul>
      <% @attendance.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  
  <div class="field">
    <%= f.label :present_days %><br>
    <%= f.number_field :present_days %>
  </div>
  <div class="field">
    <%= f.label :total_days %><br>
    <%= f.number_field :total_days %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/attendances/edit_all.html.erb
<div style="padding-top: 60px">
<%= form_for :attendance, :url => update_all_path, :html => { :method => :put } do %>
  <table>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>E-Mail</th>
    </tr>
    <% @attendance.each do |attendance| %>
      <%= fields_for "attendance[]", attendance do |attendance_fields| %>
    <tr>
      <td><%= attendance_fields.text_field :user_id %></td>
      <td><%= attendance_fields.text_field :present_days %></td>
      <td><%= attendance_fields.text_field :total_days %></td>
    </tr>
      <% end %>
    <% end %>
  </table>

  <div class="actions">
    <%= submit_tag %>
  </div>
<% end %>
</div>

app/views/attendances/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Attendances</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Present days</th>
      <th>Total days</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @attendances.each do |attendance| %>
      <tr>
        <td><%= attendance.user.profile.name %></td>
        <td><%= attendance.present_days %></td>
        <td><%= attendance.total_days %></td>
        <td><%= link_to 'Show', attendance %></td>
        <td><%= link_to 'Edit', edit_attendance_path(attendance) %></td>
        <td><%= link_to 'Destroy', attendance, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Attendance', new_attendance_path %>
</br><%= link_to 'back to dashboard', adminprofile_profile_path %>
<td><%= link_to "Edit all", {:controller => 'attendances' , :action => 'edit_all'} %></td>

app/views/attendances/new.html.erb
<h1>New Attendance</h1>

<%= render 'form' %>

<%= link_to 'Back', attendances_path %>

app/views/attendances/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Present days:</strong>
  <%= @attendance.present_days %>
</p>

<p>
  <strong>Total days:</strong>
  <%= @attendance.total_days %>
</p>

<%= link_to 'Edit', edit_attendance_path(@attendance) %> |
<%= link_to 'Back', attendances_path %>
</br><%= link_to 'back to dashboard', adminprofile_profile_path %>